[project]
name = "prompt-assistant"
version = "1.0.0"
description = "Prompt Assistant is a custom extension that realizes functions such as prompt translation, expansion, image prompt reverse-engineering, preset Tag insertion, and historical record management without adding any nodes."
readme = "README.md"
license = {text = "GNU General Public License v3"}
classifiers = [
    "Operating System :: OS Independent"  
]

[project.urls]
Repository = "https://github.com/yawiii/comfyui_prompt_assistant"


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.comfy]
PublisherId = "Yawiii"
DisplayName = "Prompt Assistant" 
Icon = "https://example.com/icon.png" 